### ISSUE TITLE
Runtime error in Debug mode for some HL examples

### ISSUE THREAD

**Issue by vmagnin** [vmagnin/gtk-fortran#131]
**Describe the bug**
These examples works OK in Release mode: hl_assistant.f90, hl_combo.f90, hl_containers.f90, hl_list_n.f90, hl_list_renderers.f90, hl_list1.f90, hl_menu.f90, hl_radio.f90, hl_sliders.f90, hl_sliders2.f90, hl_tree.f90

But in Debug mode (GTK 2 & 3) you obtain that runtime error:
```
$ ./hl_combo
 Exit called
At line 39 of file gtk-fortran/examples/hl_combo.f90
Fortran runtime error: Recursive call to nonrecursive procedure 'my_destroy'

Error termination. Backtrace:
#0  0x7fe69493d91a in ???
#1  0x7fe69493e4b5 in ???
...
```

**Your system:**
* Kubuntu 18.10 64 bits, gfortran 8.2.0
* Windows 7 MSYS2-MINGW64 (gfortran 8.2.1, gtk 3.24.5)

**Additional context**
The other hl_* examples are not affected.

**Comment by vmagnin** [comment]
I removed the `call gtk_widget_destroy(window)` from the following subroutine:
```
  subroutine my_destroy(widget, gdata) bind(c)
	type(c_ptr), value :: widget, gdata
	print *, "Exit called"
	call gtk_widget_destroy(window)
	call gtk_main_quit ()
  end subroutine my_destroy
```
Everything is now running OK in both branches.
