### ISSUE TITLE
hl_list1 example problem in Debug mode when deleting a row

### ISSUE THREAD

**Issue by vmagnin** [vmagnin/gtk-fortran#134]
**Describe the bug**

```
Delete row:           9
At line 53 of file gtk-fortran/examples/hl_list1.f90
Fortran runtime error: Recursive call to nonrecursive procedure 'list_select'

Error termination. Backtrace:
#0  0x7fe82634591a in ???
#1  0x7fe8263464b5 in ???
```

**To Reproduce**
1. Compile in Debug mode. 
2. Click in the "Delete line" box
3. Select a line
...

**Your system:**
 - Ubuntu 18.10 64 bits
 - gfortran 8.2.0
- Debug mode

**Additional context**
Tested only in gtk3 branch.

**Comment by vmagnin** [comment]
Solved by making the procedure recursive.
