### ISSUE TITLE
gtkf-sketcher crashes on example output

### ISSUE THREAD

**Issue by lllaxmatist** [vmagnin/gtk-fortran#281]
**Describe the bug**
gtkf-sketcher crashes both in gtk3 and gtk4 branches. Crashes happen on any .glade file opening attempt.
gtk4 crash on example.glade export attempt <- the only case of program opening
gtk3 crash on example.glade opening attempt

Pastebin:
[Output with GTK4](https://pastebin.com/TYqGmkeK)
[Output with GTK3](https://pastebin.com/0CB7xmbx) 

**Your system:**
 - OS version: Windows 10 x64, MSYS2-UCRT64
 - Compiler version: mingw-w64-ucrt-x86_64-gcc-fortran 13.2.0-6
 - GTK branch: gtk4 and gtk3

**Comment by vmagnin** [comment]
Thanks @lllaxmatist for reporting,

I can confirm this MSYS/Windows 10 bug. I have obtained the same segfault message, although curiously at first launch only I also had a lot of:
```shell
(process:11752): GLib-GIO-CRITICAL **: 20:54:43.315: GFileInfo created without standard::type

(process:11752): GLib-GIO-CRITICAL **: 20:54:43.316: file ../glib-2.80.0/gio/gfileinfo.c: line 1610
(g_file_info_get_file_type): should not be reached
```
(Quite similar to https://gitlab.gnome.org/GNOME/gimp/-/issues/9994)

Unhappily, most of the time bugs encountered in MSYS2 or macOS are on the GTK side and we can not do much, just report it when we have enough information. When possible, I will try also on macOS or FreeBSD.

Note also that gtkf-sketcher was never totally ported to GTK 4 due to important API changes: https://github.com/vmagnin/gtk-fortran/issues/207
I would say that the probability that I will never succeed porting it (by lack of knowledge and lack of time) is well >50%.

**Comment by vmagnin** [comment]
Interestingly, gtk4 branch also crashes on FreeBSD when clicking on "Write Files":
```shell
~/gtk-fortran/build/sketcher]$ ./gtkf-sketcher
 PWD: /home/vmagnin/gtk-fortran/build/sketcher
 symbols for all widgets =  T
 use high level interface =  T

(process:92987): GVFS-RemoteVolumeMonitor-WARNING **: 21:33:04.077: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported
 Removed from GTK 4: edit_filters, gtk_file_chooser_set_extra_widget
 1) Working dir: /home/vmagnin/gtk-fortran/build/sketcher
 2) Working dir: /home/vmagnin/gtk-fortran/build/sketcher/example
 Generating the .f90 files...
 /home/vmagnin/gtk-fortran/build/sketcher/example                                                                                                                                                                                                                
sh: python3: not found
Fortran runtime error: EXECUTE_COMMAND_LINE: Invalid command line

Error termination. Backtrace:
#0  0x82ca201f9 in ???
[...]
#5  0x40b6a1 in write_files
	at /home/vmagnin/gtk-fortran/build/sketcher/gtkf-sketcher.out.f90:530
#6  0x829f2fc2d in ???
[...]
#36  0x828e1c5b8 in ???
#37  0x41499b in gtkfsketcher
	at /home/vmagnin/gtk-fortran/build/sketcher/gtkf-sketcher.out.f90:858
#38  0x4149db in main
	at /home/vmagnin/gtk-fortran/build/sketcher/gtkf-sketcher.out.f90:800
```
But it may be another problem (" EXECUTE_COMMAND_LINE: Invalid command line").

**Comment by vmagnin** [comment]
> gtk4 crash on example.glade export attempt <- the only case of program opening

Does not happen anymore in MSYS2 UCRT64 / Windows 10 ; GFortran 14.2.0 ; latest gtk4 and gtk3 branch.

**Comment by vmagnin** [comment]
The problem does not occur anymore in FreeBSD 14.1.
